### ISSUE TITLE
Is it possible to send local files (not  by URL)?

### ISSUE THREAD

**Issue by Warmbellycat** [botman/driver-telegram#100]
- BotMan Version: 2.6
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
I try to add local image to OutgoingMessage and recieve error 400 from telegram.
Is it possible to send local files to TG?

### Steps To Reproduce:
        $attachment = new BotmanImageAttachment($image->getPathname(), ['custom_payload' => true]);
        $message = OutgoingMessage::create($messageText)->withAttachment($attachment);
Response:
"{"ok":false,"error_code":400,"description":"Bad Request: wrong remote file identifier specified: Wrong character in the string"}"

**Comment by vdomah** [comment]
Not possible using OutgoingMessage. Need to make custom request to match sendPhoto method: https://core.telegram.org/bots/api#sendphoto

**Comment by Warmbellycat** [comment]
> Not possible using OutgoingMessage. Need to make custom request to match sendPhoto method: https://core.telegram.org/bots/api#sendphoto
> 

Thanks for reply. I've write my own wrapper for this driver.
