### ISSUE TITLE
How to send video via telegram bot

### ISSUE THREAD

**Issue by Odilbukh** [botman/driver-telegram#103]
- BotMan Version: 2.0
- PHP Version: 7.4
- Messaging Service(s): Telegram
- Cache Driver: Laravel

### Description:
How to send video via telegram bot to user. Please help
I installed Telegram driver on to BotManStudio. It works good! But I can't send video to user via telegram bot

I tried this. But it does not work

```
$attachment = new Video($url);
    $message = OutgoingMessage::create()->withAttachment($attachment);

   $bot->reply($message);

```
### Steps To Reproduce:

**Comment by filippotoso** [comment]
I just tested this code and it works perfectly:

```php
// Create attachment
$attachment = new Video('https://download.samplelib.com/mp4/sample-5s.mp4', [
    'custom_payload' => true,
]);

// Build message object
$message = OutgoingMessage::create('This is a test')
    ->withAttachment($attachment);

$bot->reply($message);
```
