### ISSUE TITLE
How to get callback_query_id into Conversation

### ISSUE THREAD

**Issue by Odilbukh** [botman/driver-telegram#106]
- BotMan Version: 2.7.6
- PHP Version: 8.1
- Messaging Service(s): 
- Cache Driver:
- Laravel 9.11

### Description:

How to get callback_query_id from ?

### Steps To Reproduce:

```
 $this->ask($inline_keyboard, function (Answer $answer) use ($textMessage) {
            $selectedText = $answer->getText();
            $selectedValue = $answer->getValue();
            
            if ($selectedValue == "plus"){
                $this->bot->sendRequest('answerCallbackQuery', [
                    'callback_query_id' => 'HERE NEED callback_query_id',
                    'text' => "+ 1 товар"
                ]);
            }
```
            ........
            
            
![image](https://user-images.githubusercontent.com/22895615/179344508-ee15204c-7199-4186-aa1d-811398ed1075.png)

**Comment by filippotoso** [comment]
In 2.0.6 you'll be able to call $answer->getCallbackId()
