### ISSUE TITLE
Telegram public channel 'hearing messages'

### ISSUE THREAD

**Issue by iampuma** [botman/driver-telegram#22]
The returned payload of a public channel message and DM message are structured differently. 

So the following works in a DM, however not in public channels.

```php
$botman->hears('keyword', function($bot) {
    $bot->reply('I heard you! :)');
});
```

What is suggested for making this work in a Telegram channel?

**Comment by iampuma** [comment]
So I realised that I actually needed a group channel instead of a channel. However above question could still benefit others.

**Comment by LeonAlvarez** [comment]
Channels are 1 direction communication only

**Comment by instabot42** [comment]
Bots can be added as admins and can be used to push news / event to the channel. Worth adding support imho. Requires something like this being added to `buildPayload()`

```
        if (empty($message)) {
            $message = $this->payload->get('channel_post');
            $message['from'] = ['id' => 0];
        }
```

**Comment by feralheart** [comment]
@instabot42 Thank you for you comment. I made a PR with these rows.
