### ISSUE TITLE
"date": field

### ISSUE THREAD

**Issue by Giorat** [botman/driver-telegram#27]
I'm trying to understand when can I extend your driver to get the telegram "date" of a message.

In my bot I'd love to get the user datetime sent by Telegram POST request on every message to handle some logic.

Is it possible?

**Comment by christophrumpel** [comment]
Hey @Giorat , is the time in the payload? You can grab the whole payload for every message with `$bot->getMessage()->getPayload()`.

**Comment by Giorat** [comment]
Thank you so much @christophrumpel 👍 but this could be useful for anyone, should add it to the documentation of botman because searching payload on the documentation doesn't show anything 😢

**Comment by christophrumpel** [comment]
Yeah you're right. I will add it 👍
