### ISSUE TITLE
Botman with Telegram driver removes Keyboard from chat

### ISSUE THREAD

**Issue by adellantado** [botman/driver-telegram#29]
When I try to send message like this:
```
bot->reply('blabla', [
            'reply_markup' => json_encode(Collection::make([
            'inline_keyboard' => [ ... ]
        ]))
]);
```
After click on a button , all keyboard will be removed instantly.

I found these lines in listen() method:

```
               if (method_exists($this->getDriver(), 'messagesHandled')) {
                    $this->getDriver()->messagesHandled();
                }
```
Which calls removeInlineKeyboard().
Is it possible to add some kind of manual switcher for this feature? Or better just automatically control if it was a Question, than removeInlineKeyboard, otherwise - don't?

Versions:
"botman/botman": "2.1.10",
"botman/driver-telegram": "1.4",

**Comment by Lloople** [comment]
You can extend TelegramDriver and change the behaviour of `messagesHandled`

**Comment by adellantado** [comment]
Indeed, why I didn't come up with it. Thanks, man!

**Comment by antimech** [comment]
@Lloople @adellantado I understand how to extend the class but I don't understand how I can override it in Botman Studio on higher level. Could you please explain me? I have Conversation class and I don't want my FAQ buttons to disappear.

**Comment by aliwesome** [comment]
@adellantado 
I found easy solution for that, according to config that has been used in TelegramDriver class, you can easily set `'hideInlineKeyboard' => false,` in `config/botman/telegram.php` that would be the answer.
