### ISSUE TITLE
Can't sendRequest with custom chat_id

### ISSUE THREAD

**Issue by decadence** [botman/driver-telegram#36]
Let's say I want `sendRequest` with custom chat_id like this without `hears` method:

```php
$bot->sendRequest("pinChatMessage", [
        "chat_id" => $chatId,
        "message_id" => $messageId,
]);
```

This is not going to work because `sendRequest` always replaces my chat_id with Message.

```php
$parameters = array_replace_recursive([
    'chat_id' => $matchingMessage->getRecipient(),
], $parameters);
```

In case we are not in `hears` method it will be null so nothing works.
Can you provide a way to pass custom chat_id?

**Comment by decadence** [comment]
Ok, I forgot how `array_replace_recursive` works. So my chat_id will have priority.
But there is another problem: we have to load driver manually (like `say` method does):

```php
$bot->setDriver(DriverManager::loadFromName(TelegramDriver::class, $config));

$bot->sendRequest("pinChatMessage", [
  "chat_id" => $chatId,
  "message_id" => 40,
]);
```

Can you load inside sendRequest like in `say` method?

**Comment by kubk** [comment]
You can call `loadDriver` in your bootstrap file. From the docs: 
```php
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);

// Create BotMan instance
BotManFactory::create($config);
```

https://botman.io/2.0/driver-telegram

**Comment by decadence** [comment]
It's different thing. You have to setDriver even if you loadDriver before (say method does it for example). Without loadDriver nothing is going to work at all.

**Comment by dondap** [comment]
anyone found a solution to this?
