### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by decadence** [botman/driver-telegram#46]
Can Botman connect to Telegram API via SOCKS5 or MTProto proxy? For example in Russia Telegram is blocked and API can't be used directly

**Comment by kubk** [comment]
I think it is not available out of the box. Botman uses curl_* functions for sending HTTP requests: https://github.com/botman/botman/blob/2.0/src/Http/Curl.php#L8

It is possible to extend `BotMan\BotMan\Http\Curl` and add something like `curl_setopt($ch, CURLOPT_PROXY, 'socks5://bob:marley@ip:port');` to `prepareRequest` method here: https://github.com/botman/botman/blob/2.0/src/Http/Curl.php#L56

@mpociot My suggestion is to add an optional Guzzle adapter for `BotMan\BotMan\Interfaces\HttpInterface`: https://github.com/botman/botman/blob/2.0/src/Interfaces/HttpInterface.php

Guzzle already [supports](http://docs.guzzlephp.org/en/latest/request-options.html#proxy) proxy (can be configured using constructor). It also has many useful middlewares for [caching](https://github.com/Kevinrob/guzzle-cache-middleware), [testing](http://docs.guzzlephp.org/en/stable/testing.html), [logging](https://stackoverflow.com/a/32684940).

So this functionality can be delegated to a vendor library.

**Comment by decadence** [comment]
@kubk thanks. I hope @mpociot will consider this necessity because extending core classes is not very convenient way for such small task. Moreover you're right that underlying tools supports proxy.

**Comment by barryvdh** [comment]
Well there is an interface, so you could just create your own local client and use that?
