### ISSUE TITLE
Error retrieving user info

### ISSUE THREAD

**Issue by gawielgo** [botman/driver-telegram#56]
When I try to start a conversation with a user who has already had a conversation with a Telegram bot, I receive the following error message: 

BotMan\Drivers\Telegram\Exceptions\TelegramException: Error retrieving user info

It would seem not to be able to recover the infamous chat_id, you have any suggestions about it???

Versions:
"botman/botman": "2.4.1",
"botman/driver-telegram": "1.5.2"

**Comment by antimech** [comment]
You should at least check exception details.

**Comment by maheralmatari** [comment]
add TELEGRAM_TOKEN
