### ISSUE TITLE
Messages not being received from Telegram

### ISSUE THREAD

**Issue by acosonic** [botman/driver-telegram#61]
The only thing I see comming to my server is:

```
149.154.167.217 - - [25/Mar/2019:15:07:51 +0100] "POST /botman HTTP/1.1" 500 132738 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:07:57 +0100] "POST /botman HTTP/1.1" 500 132729 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:07:59 +0100] "POST /botman HTTP/1.1" 500 132723 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:08:03 +0100] "POST /botman HTTP/1.1" 500 132733 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:08:06 +0100] "POST /botman HTTP/1.1" 500 132745 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:08:08 +0100] "POST /botman HTTP/1.1" 500 132743 "-" "-"
149.154.167.217 - - [25/Mar/2019:15:08:12 +0100] "POST /botman HTTP/1.1" 500 132757 "-" "-"

```
But anything I type on Telegram isn't getting thru?

Webhook is properly registered

> Your bot is now set up with Telegram's webhook!
> {#665
>   +"ok": true
>   +"result": true
>   +"description": "Webhook is already set"
> }
>

**Comment by acosonic** [comment]
After a while, I have found in logs, that CURL is missing, 
`local.ERROR: Call to undefined function BotMan\BotMan\Http\curl_init() 
`
Can you add some detection like is CURL enabled, or anything other that's required, so it won't install telegram driver, unless curl is enabled...?

**Comment by germanow** [comment]
I had the same issue! I think this is because "ext-curl" located in require-dev section.
