### ISSUE TITLE
Class 'BotMan\BotMan\Messages\Attachments\Contact' not found

### ISSUE THREAD

**Issue by komarove** [botman/driver-telegram#96]
- BotMan Version: 2.4.1
- PHP Version: 7.2

### Description: 
When I send contact to bot I got error in ```vendor\\botman\\driver-telegram\\src\\TelegramContactDriver.php```.
There is no class ```BotMan\BotMan\Messages\Attachments\Contact```

### Steps To Reproduce:
Send contact to bot.

**Comment by filippotoso** [comment]
I just tested this code and it works correctly.

```php
        $this->askForContact('Please share a contact.', function ($contact) {
            $this->say(print_r($contact, true));
        });
```
