### ISSUE TITLE
How to use Keyboard

### ISSUE THREAD

**Issue by burakerenel** [botman/driver-telegram#97]
- BotMan Version: #.#.#
- PHP Version: 7.4.1
- Messaging Service(s): Telegram
- Cache Driver: Telegram

### Description:
Hello, please type a using Keyboard and callback example. Thanks

**Comment by manavy1998** [comment]
Hello, even I have been searching for this. @burakerenel please share if you figured it out.

**Comment by filippotoso** [comment]
Solved in  #66
